### ISSUE TITLE
Error on Windows 7

### ISSUE THREAD

**Issue by Alloyd031** [srwi/EverythingToolbar#340]
### Discussed in https://github.com/srwi/EverythingToolbar/discussions/339

<div type='discussions-op-text'>

<sup>Originally posted by **Alloyd031** March  3, 2023</sup>
Activating EverythingToolbar on Windows 7 throws an exception. Can someone help?</div>

**Comment by srwi** [comment]
Hi @Alloyd031, usually when requesting help it is useful to provide as much information as possible that helps other people understand the problem. In this case I would be interested in the exact exception message you are getting. Also the version number of EverythingToolbar you are using is quite important. Please also include the output of the log file. You can find it by putting `%TEMP%\EverythingToolbar.log` into the address bar of Windows explorer.

**Comment by Alloyd031** [comment]
2023-03-28 21:26:48.2131|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.0.3.0 started. OS: Microsoft Windows NT 6.1.7601 Service Pack 1|
2023-03-28 21:26:49.7432|ERROR|CSDeskBand.Deskband|Unhandled exception|System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'EverythingToolbar.Behaviors.ThemeAwareness' that matches the specified binding constraints threw an exception. ---> System.TypeLoadException: Could not find Windows Runtime type 'Windows.UI.ViewManagement.UISettings'. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
   at EverythingToolbar.Behaviors.ThemeAwareness..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at EverythingToolbar.ToolbarControl..ctor() in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar.Deskband\ToolbarControl.xaml.cs:line 20
   at CSDeskBand.Deskband..ctor() in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar.Deskband\Deskband.cs:line 24

**Comment by srwi** [comment]
Thank you. I implemented a fix for that.

**Comment by ExtremeXT** [comment]
@srwi Hi, I still have this issue on Windows 7, I'm on the latest build.

[EverythingToolbar.log](https://github.com/srwi/EverythingToolbar/files/11856894/EverythingToolbar.log)

**Comment by srwi** [comment]
Hi @ExtremeXT, unfortunately Windows 7 will not be supported anymore because I have no way to debug it.

**Comment by ExtremeXT** [comment]
@srwi 

How about something like a VM? I can debug tests if you wish.

**Comment by srwi** [comment]
I already tried setting up a VM but had some problems so I lost interest in working on it. Sorry about that. 

I am happy to accept pull requests though!
