### ISSUE TITLE
Shift+Home/End does not highlight line in deskband, home/end do not move text caret

### ISSUE THREAD

**Issue by Alfamari** [srwi/EverythingToolbar#469]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.3.2.0

### Everything Version

1.4.1.1024 (x64)

### Windows Version

Windows 10 Home Version: 22H2

### Steps to reproduce

Type something in the deskband, hold shift and hit home or end key.

Or just hit home or end key.

### Expected Behavior

Highlights from the cursor/caret position to either the beginning or end of the line if holding shift.
Otherwise moves text caret to beginning or end of line if not holding shift.

### Actual Behavior

Shift is ignored completely, home/end select the first/last entry of the results instead of manipulating the cursor/caret position in the text box despite the text box being in focus.

### Log output

2023-11-29 14:06:08.7843|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.3.2.0 started. OS: Microsoft Windows NT 10.0.19045.0|
2023-11-29 17:22:37.6479|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|

### Additional Information

Works as intended in the main program window, just not in the deskband.

**Comment by bolte-io** [comment]
I am also experiencing this issue on the latest version, and the prior 1.31 version

**Comment by informagico** [comment]
Same experience here on Windows 11 23H2 and EverythingToolbar 1.3.2.0

**Comment by srwi** [comment]
The problem has been fixed and will be available in the next release.

**Comment by yyjdelete** [comment]
@srwi 
`home/end` still not move the cursor in text, 
Instead, it move the file chooser, which look strange.(home/end in notepad move to head/end of the same line(left/right only and no up/down)
If the current behavior will be kept, hope there is an option for that.

**Comment by srwi** [comment]
> @srwi `home/end` still not move the cursor in text, Instead, it move the file chooser, which look strange.(home/end in notepad move to head/end of the same line(left/right only and no up/down) If the current behavior will be kept, hope there is an option for that.

This is by design whenever the option "Select first result" is enabled as the keyboard focus will be on the search result (if applicable) rather than the text box

**Comment by Nebur99** [comment]
> This is by design whenever the option "Select first result" is enabled as the keyboard focus will be on the search result (if applicable) rather than the text box

Imho a poor design choice - I landed here with the plan to open an issue because HOME / END didn't work - it was really the first thing I noticed when trying this otherwise wonderful little tool.

The corresponding setting should be clear on this 'little detail'. For a 'power user' it turns the search field into a nightmare when trying to refine search results with wildcards or - god forbid - using regex :-)

Wouldn't it be more intuitive to leave all 'horizontal' cursor manipulation keys dedicated to the text field - simply standard and according to user expectation?  We have the vertical keys to select a result in the list and pgup / pgdwn do a good enough job to get to the top/bottom.  Additionally keeping the perceived keyboard focus fixed on the text field would be gold.

**Comment by srwi** [comment]
> Imho a poor design choice - I landed here with the plan to open an issue because HOME / END didn't work - it was really the first thing I noticed when trying this otherwise wonderful little tool.
> 
> The corresponding setting should be clear on this 'little detail'. For a 'power user' it turns the search field into a nightmare when trying to refine search results with wildcards or - god forbid - using regex :-)
> 
> Wouldn't it be more intuitive to leave all 'horizontal' cursor manipulation keys dedicated to the text field - simply standard and according to user expectation? We have the vertical keys to select a result in the list and pgup / pgdwn do a good enough job to get to the top/bottom. Additionally keeping the perceived keyboard focus fixed on the text field would be gold.

I created a ticket for this: https://github.com/srwi/EverythingToolbar/issues/683
